# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git' 

# ignore all warnings from all pods
inhibit_all_warnings!
#use frameworks like in Obj C
 use_frameworks!  


 platform :ios, '8.0'  
 pod 'SDWebImage', '~>3.7'  